name: drop pipeline

on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  test-build-and-push-prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      containerName: ${{ steps.push.outputs.container }}
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      PROJECT_ID: august-journey-434715-u0
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.5

    - name: Build the prod Docker image
      run: make docker-build-prod

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: august-journey-434715-u0
        workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
        token_format: 'access_token'
        service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Tag and push image to prod and GCP
      id: push
      run: |
        export VERSION=$(gcloud artifacts docker tags list europe-west1-docker.pkg.dev/august-journey-434715-u0/lore-keeper-be-prod | tail -n 1 |  awk '{print $1}')
        export NEW_VERSION=$(./increment_semver.sh ${VERSION})
        gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet --access-token-file ${{ steps.auth.outputs.access_token }}
        docker tag lore-keeper-be-prod europe-west1-docker.pkg.dev/august-journey-434715-u0/lore-keeper-be/lore-keeper-be-prod:${NEW_VERSION}
        docker push europe-west1-docker.pkg.dev/august-journey-434715-u0/lore-keeper-be/lore-keeper-be-prod:${NEW_VERSION}

  deploy:
    needs: [test-build-and-push-prod]
    runs-on: ubuntu-latest
    steps:
    - name: Run stuff
      run: echo "run stuff"