name: patch pipeline

on:
  push:
    branches-ignore:
      - master

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.5

    - name: Run unit tests
      run: go test ./...

    - name: Build the app
      run: make build

    - name: Docker login
      run: |
        docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the dev Docker image
      run: make docker-build-dev

    - name: Tag and push image to dev
      run: |
        export ACCESS_TOKEN=${{ secrets.DOCKER_PASSWORD }}
        make docker-tag-and-push-dev